# Generated by Django 5.2.8 on 2026-03-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='descripcion',
            new_name='sinopsis',
        ),
        migrations.AlterUniqueTogether(
            name='peliculagenero',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='poster_url',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='peliculas/'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='reparto_info',
            field=models.TextField(blank=True),
        ),
    ]
