# Generated by Django 5.2.8 on 2026-04-27 18:53

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0003_alter_pelicula_poster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reseña',
            options={'ordering': ['-fecha']},
        ),
        migrations.RemoveField(
            model_name='likereseña',
            name='fecha_like',
        ),
        migrations.RemoveField(
            model_name='puntuacion',
            name='fecha_puntuacion',
        ),
        migrations.RemoveField(
            model_name='puntuacion',
            name='puntuacion',
        ),
        migrations.AlterUniqueTogether(
            name='reseña',
            unique_together={('usuario', 'pelicula')},
        ),
        migrations.AddField(
            model_name='likereseña',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puntuacion',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='puntuacion',
            name='valor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reseña',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reseña',
            name='puntuacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reseña',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='reseña',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='reseña',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='reseña',
            name='fecha_reseña',
        ),
    ]
