# Generated by Django 5.2.8 on 2026-04-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0004_alter_reseña_options_remove_likereseña_fecha_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntuacion',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='reseña',
            name='puntuacion',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
