# Generated by Django 5.2.8 on 2026-04-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0005_alter_puntuacion_valor_alter_reseña_puntuacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntuacion',
            name='valor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reseña',
            name='puntuacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
