# Generated by Django 5.2.8 on 2026-05-15 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0006_alter_puntuacion_valor_alter_reseña_puntuacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reseña',
            options={'ordering': ['-fecha'], 'permissions': [('puede_eliminar_reseñas', 'Puede eliminar reseñas de otros usuarios')]},
        ),
    ]
